//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chapter43_RoomServiceClientForm.RoomReservationService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RoomReservaton", Namespace="http://schemas.datacontract.org/2004/07/Chapter43_RoomReservationContracts")]
    [System.SerializableAttribute()]
    public partial class RoomReservaton : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoomNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contact {
            get {
                return this.ContactField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactField, value) != true)) {
                    this.ContactField = value;
                    this.RaisePropertyChanged("Contact");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndTime {
            get {
                return this.EndTimeField;
            }
            set {
                if ((this.EndTimeField.Equals(value) != true)) {
                    this.EndTimeField = value;
                    this.RaisePropertyChanged("EndTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoomName {
            get {
                return this.RoomNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RoomNameField, value) != true)) {
                    this.RoomNameField = value;
                    this.RaisePropertyChanged("RoomName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartTime {
            get {
                return this.StartTimeField;
            }
            set {
                if ((this.StartTimeField.Equals(value) != true)) {
                    this.StartTimeField = value;
                    this.RaisePropertyChanged("StartTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RoomReservationService.IRoomService")]
    public interface IRoomService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomService/ReserveRoom", ReplyAction="http://tempuri.org/IRoomService/ReserveRoomResponse")]
        bool ReserveRoom(Chapter43_RoomServiceClientForm.RoomReservationService.RoomReservaton roomReservaton);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomService/ReserveRoom", ReplyAction="http://tempuri.org/IRoomService/ReserveRoomResponse")]
        System.Threading.Tasks.Task<bool> ReserveRoomAsync(Chapter43_RoomServiceClientForm.RoomReservationService.RoomReservaton roomReservaton);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomService/GetRoomReservaton", ReplyAction="http://tempuri.org/IRoomService/GetRoomReservatonResponse")]
        Chapter43_RoomServiceClientForm.RoomReservationService.RoomReservaton[] GetRoomReservaton(System.DateTime fromDatetime, System.DateTime toDatetime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomService/GetRoomReservaton", ReplyAction="http://tempuri.org/IRoomService/GetRoomReservatonResponse")]
        System.Threading.Tasks.Task<Chapter43_RoomServiceClientForm.RoomReservationService.RoomReservaton[]> GetRoomReservatonAsync(System.DateTime fromDatetime, System.DateTime toDatetime);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRoomServiceChannel : Chapter43_RoomServiceClientForm.RoomReservationService.IRoomService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RoomServiceClient : System.ServiceModel.ClientBase<Chapter43_RoomServiceClientForm.RoomReservationService.IRoomService>, Chapter43_RoomServiceClientForm.RoomReservationService.IRoomService {
        
        public RoomServiceClient() {
        }
        
        public RoomServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RoomServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RoomServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RoomServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool ReserveRoom(Chapter43_RoomServiceClientForm.RoomReservationService.RoomReservaton roomReservaton) {
            return base.Channel.ReserveRoom(roomReservaton);
        }
        
        public System.Threading.Tasks.Task<bool> ReserveRoomAsync(Chapter43_RoomServiceClientForm.RoomReservationService.RoomReservaton roomReservaton) {
            return base.Channel.ReserveRoomAsync(roomReservaton);
        }
        
        public Chapter43_RoomServiceClientForm.RoomReservationService.RoomReservaton[] GetRoomReservaton(System.DateTime fromDatetime, System.DateTime toDatetime) {
            return base.Channel.GetRoomReservaton(fromDatetime, toDatetime);
        }
        
        public System.Threading.Tasks.Task<Chapter43_RoomServiceClientForm.RoomReservationService.RoomReservaton[]> GetRoomReservatonAsync(System.DateTime fromDatetime, System.DateTime toDatetime) {
            return base.Channel.GetRoomReservatonAsync(fromDatetime, toDatetime);
        }
    }
}
